name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configue enable-fully-static
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
         name: unbound
         path: unbound 
         retention-days: 20 

      

